config/routes.rb
AddressBookApp::Application.routes.draw do
  get "static_pages/authorize"
  devise_for :users
  root :to => "home#index"
  resources :users
  resources :contacts

  namespace :api do
    resources :contacts
    resources :webhooks
    get '*path', :to => redirect("/api/%{path}")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    AddressBookApp by Pili Guerra @ <a href="http://support.3scale.net/">3scale support</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://support.3scale.net">Contact</a></li>
      <li><a href="http://www.3scale.net/category/tech-blog/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
   <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Address Book Application", root_path, id: "logo" %>
<nav>
  <ul class="nav pull-right">
     <li><%= link_to "Home", root_path  %></li>
     <% if user_signed_in? %>
     <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Contacts<b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to 'View', contacts_path %></li>
        <li><%= link_to 'New', new_contact_path %></li>
      </ul> 
    </li>
    <li id="fat-menu" class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
        </li>
      </ul>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  </ul>
</nav>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container" id="main" role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>